-- ============================================================
-- AUREVIA — content seed (generated by tool/generate_seed_sql.dart)
-- Loads the full catalogue into Supabase. Idempotent:
--   destinations/packages skip rows whose slug already exists;
--   gallery/testimonials/faqs only load into an empty table.
-- Run after schema.sql in the Supabase SQL editor.
-- ============================================================

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('kerala', 'Kerala', 'India', 'Where the backwaters keep their own time',
   'Kerala unfolds slowly — a latticework of palm-shaded canals, spice-scented hills and beaches the colour of raw silk. Drift through Alleppey aboard a private kettuvallam houseboat, wake to mist rolling over Munnar''s tea terraces, and end each evening with Kathakali fire and coastal seafood. This is India at its most unhurried, curated down to the last cardamom pod.',
   'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/2169880/2169880-uhd_3840_2160_30fps.mp4', 24500, 6, 5,
   'September – March', 4.9, 1284, true,
   '["Honeymoon","Family","Nature"]'::jsonb,
   '["Private houseboat night on the Alleppey backwaters","Sunrise walk through Munnar tea plantations","Kathakali performance with backstage access","Ayurvedic spa ritual at a heritage resort","Canoe village tour through Kumarakom","Fort Kochi heritage walk and Chinese fishing nets at dusk"]'::jsonb,
   '[{"day":1,"title":"Arrival in Kochi","description":"Private transfer to a restored Dutch-era heritage hotel in Fort Kochi. Evening walk past St. Francis Church and the Chinese fishing nets, followed by a seafood dinner on the harbour."},{"day":2,"title":"Kochi to Munnar","description":"A cinematic four-hour climb into the Western Ghats, pausing at waterfalls and spice gardens. Check in to a plantation bungalow wrapped in tea."},{"day":3,"title":"Munnar tea country","description":"Sunrise at Top Station, a guided tasting at a working tea factory, and an afternoon at leisure among the terraces of Kolukkumalai."},{"day":4,"title":"Munnar to Alleppey","description":"Descend to the backwaters and board your private kettuvallam. Lunch is cooked aboard as you drift past paddy fields and village jetties."},{"day":5,"title":"Kumarakom","description":"Morning canoe through narrow village canals, then an Ayurvedic abhyanga ritual at a lakeside resort. Sunset over Vembanad Lake."},{"day":6,"title":"Departure","description":"A slow breakfast on the water before your private transfer to Kochi International Airport."}]'::jsonb,
   '["Five nights in heritage and plantation stays","Private exclusive-use houseboat with chef","All transfers in a private chauffeured vehicle","Daily breakfast and four curated dinners","English-speaking destination host throughout","Kathakali performance and tea factory access"]'::jsonb,
   '["Flights to and from Kochi","Personal expenses and gratuities","Travel insurance","Lunches on days 2 and 3","Camera fees at monuments"]'::jsonb,
   '[{"name":"Brunton Boatyard","stars":5,"location":"Fort Kochi","image":"https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=75"},{"name":"Windermere Estate","stars":4,"location":"Munnar","image":"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=75"},{"name":"Kumarakom Lake Resort","stars":5,"location":"Kumarakom","image":"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Athirappilly Falls","distance":"55 km from Kochi","description":"Kerala''s largest waterfall, thundering through rainforest."},{"name":"Eravikulam National Park","distance":"13 km from Munnar","description":"Home of the endangered Nilgiri tahr and rolling shola grasslands."},{"name":"Marari Beach","distance":"15 km from Alleppey","description":"An undeveloped fishing coast of coconut palms and quiet sand."}]'::jsonb,
   '[{"author":"Ananya Iyer","origin":"Bengaluru","rating":5.0,"comment":"The houseboat evening alone was worth the trip. Aurevia thought of everything — even the playlist on board matched the sunset.","month_year":"January 2026"},{"author":"James & Clara Whitmore","origin":"London","rating":5.0,"comment":"Our honeymoon was flawless. The plantation bungalow in Munnar felt like a film set, and our host Vipin was extraordinary.","month_year":"November 2025"},{"author":"Rohit Menon","origin":"Mumbai","rating":4.5,"comment":"Took my parents and my kids — every generation found something to love. Seamless logistics.","month_year":"December 2025"}]'::jsonb,
   9.4981, 76.3388, 'Kerala Luxury Tour Packages — Backwaters, Munnar & Kochi', 'Private houseboats, plantation stays and Ayurvedic rituals. Curated 6-day Kerala journeys by Aurevia.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('kashmir', 'Kashmir', 'India', 'A valley the poets never exaggerated',
   'Srinagar''s houseboats, saffron fields of Pampore, the alpine amphitheatres of Gulmarg and Pahalgam — Kashmir remains the subcontinent''s most romantic landscape. We arrange cedar-panelled houseboat suites on Dal Lake, private shikara flotillas at dawn, and mountain lunches served on meadows at ten thousand feet.',
   'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/3571264/3571264-uhd_3840_2160_30fps.mp4', 32000, 6, 5,
   'April – October', 4.8, 942, true,
   '["Honeymoon","Adventure","Nature"]'::jsonb,
   '["Cedar houseboat suite on Dal Lake","Dawn shikara ride through the floating market","Gulmarg gondola to Apharwat ridge","Private meadow lunch in Pahalgam","Mughal gardens after closing hours","Saffron and pashmina ateliers with the makers"]'::jsonb,
   '[{"day":1,"title":"Srinagar arrival","description":"Met at the tarmac and transferred by shikara to your houseboat suite. Kahwa tea on the deck as the light drops behind Hari Parbat."},{"day":2,"title":"Dal Lake & old Srinagar","description":"Dawn at the floating vegetable market, then the old city''s papier-mâché and pashmina workshops. Evening in Nishat Bagh, opened privately."},{"day":3,"title":"Gulmarg","description":"Drive to the meadow of flowers. Ride the world''s second-highest gondola and lunch at a slope-side chalet."},{"day":4,"title":"Pahalgam","description":"Through saffron country to the Lidder valley. Afternoon pony trek to Baisaran meadow, dinner beside the river."},{"day":5,"title":"Betaab & Aru valleys","description":"A slow day among pines and glacial streams with a private picnic. Return to Srinagar by evening."},{"day":6,"title":"Departure","description":"Breakfast on the water, a last walk through Shalimar Bagh, and your transfer to the airport."}]'::jsonb,
   '["Two nights in a heritage houseboat suite","Three nights in alpine resorts","Private vehicle and driver throughout","Gondola tickets to Apharwat","Daily breakfast and dinner","Destination host and all permits"]'::jsonb,
   '["Flights to and from Srinagar","Pony rides and sledding","Travel insurance","Lunches except where noted","Personal shopping"]'::jsonb,
   '[{"name":"Sukoon Houseboat","stars":5,"location":"Dal Lake","image":"https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=75"},{"name":"The Khyber Himalayan Resort","stars":5,"location":"Gulmarg","image":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=75"},{"name":"WelcomHotel Pine N Peak","stars":4,"location":"Pahalgam","image":"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Sonamarg","distance":"80 km from Srinagar","description":"The meadow of gold at the mouth of the Thajiwas glacier."},{"name":"Doodhpathri","distance":"42 km from Srinagar","description":"An untouched bowl of pasture and pine."},{"name":"Shankaracharya Temple","distance":"8 km from Srinagar","description":"A thousand-year-old shrine above the lake."}]'::jsonb,
   '[{"author":"Priya & Arjun Malhotra","origin":"Delhi","rating":5.0,"comment":"The private evening in Nishat Bagh was pure cinema. Kashmir with Aurevia is a different country.","month_year":"May 2026"},{"author":"Sofia Lindqvist","origin":"Stockholm","rating":4.8,"comment":"The houseboat, the kahwa, the mountains — I have never slept better anywhere.","month_year":"June 2026"}]'::jsonb,
   34.0837, 74.7973, 'Kashmir Luxury Tours — Dal Lake Houseboats, Gulmarg & Pahalgam', 'Heritage houseboats, private Mughal garden evenings and alpine meadows. 6-day Kashmir journeys by Aurevia.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('goa', 'Goa', 'India', 'Susegad — the art of unhurried joy',
   'Beyond the beach shacks lies another Goa: Indo-Portuguese mansions draped in bougainvillea, Latin Quarter lanes in Fontainhas, spice farms up the Mandovi and quiet southern sands where turtles still nest. We pair heritage stays with sunset sails, market breakfasts and tables at the state''s finest kitchens.',
   'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1520454974749-611b7248ffdb?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1530521954074-e64f6810b32d?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/1093662/1093662-hd_1920_1080_30fps.mp4', 18900, 5, 4,
   'November – February', 4.7, 1567, false,
   '["Weekend","Family","Beach"]'::jsonb,
   '["Private sunset catamaran on the Arabian Sea","Fontainhas heritage walk with a local historian","Table at a chef-led Goan-Portuguese kitchen","Butterfly Beach by private boat","Spice plantation lunch on banana leaf","Old Goa basilicas before the crowds"]'::jsonb,
   '[{"day":1,"title":"Arrival — South Goa","description":"Transfer to a beachfront heritage resort near Betalbatim. Evening at leisure on a quiet stretch of silver sand."},{"day":2,"title":"Old Goa & Fontainhas","description":"Basilica of Bom Jesus and Sé Cathedral at opening time, then a slow walk through the Latin Quarter with feni tasting and lunch at a heritage café."},{"day":3,"title":"Spice country","description":"Up the Mandovi to a working spice farm — cardamom, peppercorn, betel. Traditional lunch, afternoon river cruise past mangroves."},{"day":4,"title":"Islands & sunset sail","description":"Private boat to Butterfly and Honeymoon beaches. Golden hour aboard a catamaran with Goan canapés."},{"day":5,"title":"Departure","description":"Beach breakfast and a private transfer to Dabolim or Mopa airport."}]'::jsonb,
   '["Four nights in a beachfront heritage resort","Private catamaran sunset sail","All excursions with private guide","Daily breakfast and two signature dinners","Airport transfers","Spice plantation experience with lunch"]'::jsonb,
   '["Flights","Alcohol beyond welcome drinks","Water sports","Travel insurance","Personal expenses"]'::jsonb,
   '[{"name":"Taj Exotica Resort & Spa","stars":5,"location":"Benaulim","image":"https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=75"},{"name":"Ahilya by the Sea","stars":4,"location":"Nerul","image":"https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Dudhsagar Falls","distance":"71 km from Panaji","description":"A four-tiered cascade on the Mandovi, best after monsoon."},{"name":"Chapora Fort","distance":"22 km from Panaji","description":"Laterite ramparts with the coast''s definitive sunset."},{"name":"Divar Island","distance":"12 km from Panaji","description":"Ferry-only island of whitewashed churches and paddy."}]'::jsonb,
   '[{"author":"Kabir & Naina Shah","origin":"Pune","rating":4.7,"comment":"We thought we knew Goa. The Fontainhas walk and the catamaran evening proved otherwise.","month_year":"December 2025"},{"author":"Emily Harper","origin":"Sydney","rating":4.8,"comment":"Elegant, easy, and never touristy. The south coast is a dream.","month_year":"January 2026"}]'::jsonb,
   15.2993, 74.124, 'Goa Luxury Escapes — Heritage, Beaches & Sunset Sails', 'Indo-Portuguese heritage, private boats and the quiet southern coast. Curated Goa escapes by Aurevia.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('ladakh', 'Ladakh', 'India', 'The last great silence',
   'A high-altitude desert of cobalt lakes, thousand-year-old gompas and passes that graze the sky. Our Ladakh journeys are built around acclimatisation and access — private monastery audiences, luxury camps on Pangong''s shore, and drives over Khardung La with oxygen, chase vehicle and a crew that has done this a hundred times.',
   'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/3571264/3571264-uhd_3840_2160_30fps.mp4', 38500, 7, 6,
   'June – September', 4.9, 731, true,
   '["Adventure","Nature","Photography"]'::jsonb,
   '["Luxury lakeshore camp at Pangong Tso","Dawn prayers with the monks of Thiksey","Khardung La — one of the world''s highest motorable passes","Bactrian camel ride in the Nubra dunes","Rafting the Zanskar confluence","Stargazing at 14,000 feet with an astronomer"]'::jsonb,
   '[{"day":1,"title":"Fly into Leh","description":"The Himalaya from your window seat, then two slow days begin. Rest, hydrate, and watch the light on Stok Kangri from your terrace."},{"day":2,"title":"Leh acclimatisation","description":"Gentle morning at Shanti Stupa and Leh Palace, afternoon in the old town''s bakeries and antique shops."},{"day":3,"title":"Monastery circuit","description":"Dawn prayers at Thiksey, the Indus valley''s great gompas — Hemis, Stakna, Matho — and lunch in a village orchard."},{"day":4,"title":"Over Khardung La to Nubra","description":"Cross 17,582 feet into the valley of flowers. Evening among the double-humped camels on the Hunder dunes."},{"day":5,"title":"Nubra to Pangong","description":"The Shyok river road to Pangong Tso. Your camp sits on the lake''s western shore; dinner under a sky thick with stars."},{"day":6,"title":"Pangong to Leh","description":"Sunrise as the lake runs through its blues, then back over Chang La with a stop at Hemis. Farewell dinner in Leh."},{"day":7,"title":"Departure","description":"Morning flight out over the ranges."}]'::jsonb,
   '["Six nights — boutique Leh stay and luxury camps","Oxygen-equipped SUV with experienced mountain driver","All inner line permits and monastery fees","Full board throughout","Astronomer-led stargazing session","Destination host and 24/7 support"]'::jsonb,
   '["Flights to and from Leh","Rafting (optional add-on)","Travel insurance with high-altitude cover","Tips and personal expenses","Anything not in inclusions"]'::jsonb,
   '[{"name":"The Grand Dragon","stars":5,"location":"Leh","image":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=75"},{"name":"TUTC Chamba Camp","stars":5,"location":"Thiksey","image":"https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1000&q=75"},{"name":"Pangong Sarai Luxury Camp","stars":4,"location":"Pangong Tso","image":"https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Magnetic Hill","distance":"27 km from Leh","description":"The optical illusion where cars appear to roll uphill."},{"name":"Alchi Monastery","distance":"66 km from Leh","description":"Eleventh-century murals unmatched in the Himalaya."},{"name":"Tso Moriri","distance":"220 km from Leh","description":"A remoter, wilder twin to Pangong in Changthang."}]'::jsonb,
   '[{"author":"Aditya Rao","origin":"Hyderabad","rating":5.0,"comment":"The stargazing night at Pangong rearranged something in me. Faultless organisation at brutal altitudes.","month_year":"August 2025"},{"author":"Marco Bianchi","origin":"Milan","rating":4.9,"comment":"I''ve done Patagonia and Iceland. Ladakh with this team tops both.","month_year":"July 2026"}]'::jsonb,
   34.1526, 77.5771, 'Ladakh Expeditions — Pangong, Nubra & Khardung La in Comfort', 'Luxury camps, monastery audiences and oxygen-equipped expeditions across the high Himalaya.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('manali', 'Manali', 'India', 'Cedar forests, river mornings, mountain air',
   'Old Manali''s orchards and the Kullu valley''s deodar forests make the Himalaya feel domestic and wild at once. We base you in a riverside lodge, send you paragliding over Solang, trekking to Jogini falls, and — in season — through the Atal tunnel to the stark beauty of Sissu and the Lahaul valley.',
   'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/1918465/1918465-uhd_3840_2160_24fps.mp4', 16500, 5, 4,
   'March – June, October – February', 4.6, 1108, false,
   '["Adventure","Weekend","Honeymoon"]'::jsonb,
   '["Riverside lodge beneath deodar forest","Paragliding over the Solang valley","Atal tunnel drive to Sissu waterfalls","Hidimba temple and Old Manali cafés","Private riverside bonfire with mountain barbecue","Jogini falls forest trek"]'::jsonb,
   '[{"day":1,"title":"Arrival","description":"Met in Kullu or at your Volvo drop point. Settle into a riverside lodge; evening walk through Old Manali''s orchard lanes."},{"day":2,"title":"Solang valley","description":"Morning paragliding and ropeway, afternoon at Hidimba temple and the Tibetan monastery. Bonfire dinner by the Beas."},{"day":3,"title":"Lahaul day","description":"Through the Atal tunnel to Sissu — waterfalls, barley fields, and the Chandra river''s glacier grey. Picnic lunch."},{"day":4,"title":"Forest trails","description":"Guided trek to Jogini falls through cedar and apple orchards. Afternoon at leisure with café time in Old Manali."},{"day":5,"title":"Departure","description":"Slow breakfast and onward transfer."}]'::jsonb,
   '["Four nights riverside boutique lodge","Paragliding with certified pilots","Private SUV for all excursions","Daily breakfast and dinner","Guided Jogini falls trek","Bonfire evening with barbecue"]'::jsonb,
   '["Transport to Manali","Ropeway tickets","Lunches","Travel insurance","Snow gear rental in winter"]'::jsonb,
   '[{"name":"Span Resort & Spa","stars":4,"location":"Kullu–Manali Highway","image":"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1000&q=75"},{"name":"The Himalayan","stars":4,"location":"Hadimba Road","image":"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Rohtang Pass","distance":"51 km from Manali","description":"The storied gateway to Lahaul, snowbound most of the year."},{"name":"Naggar Castle","distance":"21 km from Manali","description":"A fifteenth-century timber castle above the Kullu valley."},{"name":"Vashisht hot springs","distance":"3 km from Manali","description":"Sulphur springs beside an ancient stone temple."}]'::jsonb,
   '[{"author":"Sneha Kulkarni","origin":"Nagpur","rating":4.6,"comment":"Perfect long weekend. The lodge was gorgeous and the Sissu day felt like another planet.","month_year":"October 2025"},{"author":"Dhruv Kapoor","origin":"Chandigarh","rating":4.5,"comment":"Paragliding was superbly organised. Great valley knowledge.","month_year":"April 2026"}]'::jsonb,
   32.2396, 77.1887, 'Manali Getaways — Solang, Sissu & Riverside Lodges', 'Paragliding, cedar forests and the Atal tunnel to Lahaul. Curated Manali escapes by Aurevia.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('ooty', 'Ooty', 'India', 'The blue mountains, taken slowly',
   'The Nilgiris reward the unhurried: a UNESCO-listed toy train through eucalyptus and tea, colonial bungalows with fireplaces lit by six, and viewpoints where the hills genuinely turn blue at dusk. We add estate tastings, Toda village encounters and picnic hampers packed by your bungalow''s kitchen.',
   'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/857251/857251-hd_1280_720_25fps.mp4', 14900, 4, 3,
   'October – June', 4.5, 876, false,
   '["Family","Weekend","Nature"]'::jsonb,
   '["Nilgiri Mountain Railway in a reserved coach","Heritage bungalow stay with butler service","Private tea estate tasting with the planter","Doddabetta and Avalanche lake picnic","Toda hamlet visit with an anthropologist guide","Rose garden and botanical walk"]'::jsonb,
   '[{"day":1,"title":"Up the mountain","description":"Board the toy train at Mettupalayam for the climb through Coonoor''s tea. Check in to a Raj-era bungalow; scones by the fire."},{"day":2,"title":"Tea country","description":"Morning with a planter — plucking, withering, tasting. Afternoon at Sim''s Park and the Dolphin''s Nose viewpoint."},{"day":3,"title":"Lakes and peaks","description":"Doddabetta at dawn, then a hamper picnic at Avalanche lake. Evening boat on Ooty lake and the chocolate factory."},{"day":4,"title":"Departure","description":"Botanical garden stroll before the drive down."}]'::jsonb,
   '["Three nights heritage bungalow with butler","Reserved toy train seats","All drives in a private car","Daily breakfast and dinner","Estate tasting and picnic hamper","All entry fees"]'::jsonb,
   '["Transport to Mettupalayam/Coimbatore","Lunches except picnic day","Travel insurance","Personal expenses","Horse rides at the lake"]'::jsonb,
   '[{"name":"Savoy — IHCL SeleQtions","stars":5,"location":"Ooty","image":"https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=75"},{"name":"La Belle Vie","stars":4,"location":"Coonoor","image":"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Pykara falls","distance":"20 km from Ooty","description":"Cascades through shola forest with boating below."},{"name":"Mudumalai National Park","distance":"35 km from Ooty","description":"Elephant and tiger country on the Mysore road."},{"name":"Ketti valley","distance":"7 km from Ooty","description":"One of the world''s widest valleys, best at sunset."}]'::jsonb,
   '[{"author":"The Krishnamurthys","origin":"Chennai","rating":4.5,"comment":"The bungalow and butler made it. Our children still talk about the toy train.","month_year":"May 2026"},{"author":"Alan Pereira","origin":"Kochi","rating":4.4,"comment":"Genteel and green. The estate tasting was a highlight.","month_year":"January 2026"}]'::jsonb,
   11.4102, 76.695, 'Ooty Heritage Escapes — Toy Train, Tea Estates & Bungalows', 'Reserved toy-train coaches, planter tastings and Raj-era bungalows in the Nilgiris.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('munnar', 'Munnar', 'India', 'An ocean of tea at five thousand feet',
   'Munnar is what green dreams look like: fifty shades of it, combed into terraces that roll to the horizon. Stay in a planter''s bungalow inside a working estate, walk to viewpoints before the mist lifts, and take dinner beside a fireplace as cicadas start in the valley below.',
   'https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/857251/857251-hd_1280_720_25fps.mp4', 15900, 4, 3,
   'September – May', 4.7, 964, false,
   '["Honeymoon","Nature","Weekend"]'::jsonb,
   '["Planter''s bungalow inside a working estate","Kolukkumalai — the world''s highest tea, by jeep at dawn","Eravikulam National Park and the Nilgiri tahr","Tea factory masterclass and tasting flight","Candlelit estate dinner under the stars","Spice route drive to Top Station"]'::jsonb,
   '[{"day":1,"title":"Into the high ranges","description":"The climb from Kochi through waterfalls and cardamom country. Evening tea on your bungalow lawn as mist fills the valley."},{"day":2,"title":"Kolukkumalai dawn","description":"A 4 a.m. jeep to the world''s highest organic tea estate for sunrise above the clouds. Factory masterclass, afternoon at leisure."},{"day":3,"title":"Eravikulam & Top Station","description":"Morning with the Nilgiri tahr on Rajamala''s slopes, then the old spice route to Top Station''s edge-of-the-world view. Candlelit dinner."},{"day":4,"title":"Departure","description":"Estate walk and descent to Kochi."}]'::jsonb,
   '["Three nights planter''s bungalow, full board","Kolukkumalai sunrise jeep safari","Eravikulam entry and guide","Private vehicle from Kochi and back","Tea factory masterclass","Candlelit estate dinner"]'::jsonb,
   '["Flights to Kochi","Travel insurance","Ayurvedic treatments","Personal expenses","Camera fees"]'::jsonb,
   '[{"name":"Windermere Estate","stars":4,"location":"Pothamedu","image":"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=75"},{"name":"Fragrant Nature","stars":5,"location":"Chithirapuram","image":"https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Mattupetty dam","distance":"10 km from Munnar","description":"Boating between grassed hills and shola forest."},{"name":"Attukal waterfalls","distance":"9 km from Munnar","description":"A monsoon-fed fall framed by hills and tea."},{"name":"Anamudi","distance":"13 km from Munnar","description":"South India''s highest peak, inside Eravikulam."}]'::jsonb,
   '[{"author":"Ishaan & Tara Bedi","origin":"Gurgaon","rating":4.9,"comment":"The Kolukkumalai sunrise is the single best thing we have done in India.","month_year":"February 2026"},{"author":"Lakshmi Narayan","origin":"Coimbatore","rating":4.6,"comment":"Quiet, green, impeccably arranged.","month_year":"March 2026"}]'::jsonb,
   10.0889, 77.0595, 'Munnar Tea Country — Planter Bungalows & Kolukkumalai Sunrises', 'Estate stays, factory masterclasses and dawn above the clouds in Kerala''s high ranges.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('coorg', 'Coorg', 'India', 'Coffee, cardamom and Kodava hospitality',
   'Kodagu — Coorg to the Raj — is a highland of coffee estates, sacred river sources and a martial people with a cuisine all their own. Stay on a working plantation, walk its shaded acres with the owner, raft the Barapole''s rapids in season and eat pandi curry the way only a Kodava home makes it.',
   'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/1918465/1918465-uhd_3840_2160_24fps.mp4', 15500, 4, 3,
   'October – March', 4.6, 689, false,
   '["Nature","Family","Weekend"]'::jsonb,
   '["Plantation stay with the estate family","Coffee walk and cupping session","Abbey falls and Raja''s seat at golden hour","Dubare elephant camp on the Cauvery","Kodava lunch in a heritage ainmane home","Tibetan golden temple at Bylakuppe"]'::jsonb,
   '[{"day":1,"title":"Arrival in coffee country","description":"Drive up from Mysore or Mangalore through betel and paddy. Estate tea on the verandah, evening birdsong."},{"day":2,"title":"The estate day","description":"Morning coffee walk — arabica, robusta, pepper vines — with a cupping session. Afternoon at Abbey falls and Raja''s seat for sunset."},{"day":3,"title":"River and monastery","description":"Dubare elephant camp at bathing hour, coracle ride on the Cauvery, then the gilded prayer halls of Bylakuppe. Kodava lunch en route."},{"day":4,"title":"Departure","description":"Estate breakfast and the drive down."}]'::jsonb,
   '["Three nights plantation homestay, full board","Coffee walk and cupping with the planter","Private vehicle throughout","Dubare and Bylakuppe excursion","Traditional Kodava lunch experience","All entry fees"]'::jsonb,
   '["Transport to Coorg","White-water rafting (seasonal add-on)","Travel insurance","Personal expenses","Alcohol"]'::jsonb,
   '[{"name":"Old Kent Estates","stars":4,"location":"Suntikoppa","image":"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1000&q=75"},{"name":"Evolve Back Coorg","stars":5,"location":"Siddapura","image":"https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Talakaveri","distance":"48 km from Madikeri","description":"The sacred source of the Cauvery on Brahmagiri hill."},{"name":"Mandalpatti peak","distance":"18 km from Madikeri","description":"Jeep-track summit above a sea of monsoon clouds."},{"name":"Iruppu falls","distance":"48 km from Madikeri","description":"A forest fall beside the Rameshwara temple."}]'::jsonb,
   '[{"author":"Vikram Nair","origin":"Bengaluru","rating":4.7,"comment":"The estate family''s table was the best meal of my year. Coorg done right.","month_year":"November 2025"},{"author":"Meera & Sanjay Hegde","origin":"Mangalore","rating":4.5,"comment":"Restful, fragrant, beautifully paced.","month_year":"December 2025"}]'::jsonb,
   12.3375, 75.8069, 'Coorg Plantation Stays — Coffee Estates & Kodava Tables', 'Working plantations, cupping sessions and the Cauvery''s elephants in Kodagu.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('jaipur', 'Jaipur', 'India', 'The pink city, palace doors ajar',
   'Jaipur is theatre — Amber Fort''s mirrored halls, the honeycomb of Hawa Mahal, bazaars dense with gemstones and block print. We open its quieter doors: private palace dinners, textile ateliers with master printers, dawn at Amber before the gates, and a hot-air balloon drifting over the Aravallis.',
   'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1524230507669-5ff97982bb5e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1587135941948-670b381f08ce?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/2169880/2169880-uhd_3840_2160_30fps.mp4', 21900, 4, 3,
   'October – March', 4.8, 1195, true,
   '["Heritage","Family","Luxury"]'::jsonb,
   '["Amber Fort at opening hour, before the crowds","Hot-air balloon over the Aravalli hills","Private dinner in a heritage palace courtyard","Block-print atelier with a master printer","City Palace royal quarters with curator access","Gem bazaar walk with a certified gemologist"]'::jsonb,
   '[{"day":1,"title":"Arrival in the pink city","description":"Check in to a restored haveli. Evening rickshaw glide past Hawa Mahal lit for dusk, dinner on a bazaar rooftop."},{"day":2,"title":"Amber and the royal city","description":"Amber Fort at opening hour with a historian, Panna Meena stepwell, then City Palace''s royal quarters and Jantar Mantar."},{"day":3,"title":"Balloons and bazaars","description":"Dawn balloon flight over forts and dunes. Later, a block-print atelier in Sanganer and the gem bazaar with an expert. Palace courtyard dinner."},{"day":4,"title":"Departure","description":"Breakfast at the haveli, onward transfer."}]'::jsonb,
   '["Three nights heritage haveli stay","Hot-air balloon flight","Historian-led Amber and City Palace visits","Private palace courtyard dinner","All transfers in a private car","Daily breakfast"]'::jsonb,
   '["Flights or trains to Jaipur","Lunches","Travel insurance","Shopping and personal expenses","Monument camera fees"]'::jsonb,
   '[{"name":"Samode Haveli","stars":5,"location":"Gangapole","image":"https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=75"},{"name":"Alila Fort Bishangarh","stars":5,"location":"Bishangarh","image":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Nahargarh Fort","distance":"9 km from Jaipur","description":"The city''s definitive sunset rampart."},{"name":"Abhaneri stepwell","distance":"88 km from Jaipur","description":"Chand Baori''s thirteen-storey geometry."},{"name":"Sambhar salt lake","distance":"80 km from Jaipur","description":"Flamingos and salt flats shot straight from a dream."}]'::jsonb,
   '[{"author":"Charlotte Dubois","origin":"Paris","rating":5.0,"comment":"The balloon at dawn over Amber — I have no words that do it justice.","month_year":"February 2026"},{"author":"Nikhil Choudhary","origin":"Jaipur","rating":4.7,"comment":"I grew up here and they still showed me rooms I''d never seen.","month_year":"December 2025"}]'::jsonb,
   26.9124, 75.7873, 'Jaipur Royal Journeys — Amber at Dawn & Palace Dinners', 'Historian-led forts, balloon flights and haveli stays in the pink city.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('dubai', 'Dubai', 'United Arab Emirates', 'The future, with desert manners',
   'Dubai runs on superlatives, but its best moments are quiet ones: falcons at dawn over the Empty Quarter''s edge, the old creek''s abra crossings, dinner at 122 storeys as the fountains bloom below. We balance the skyline with the sand — five-star towers and a night in a desert conservation reserve.',
   'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1526495124232-a04e1849168c?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1523816572877-2789929ae3ae?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1489516408517-0c0a15662682?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1512632578888-169bbbc64f33?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/2169880/2169880-uhd_3840_2160_30fps.mp4', 58000, 5, 4,
   'November – March', 4.8, 1436, true,
   '["Luxury","Family","International"]'::jsonb,
   '["At the Top — Burj Khalifa level 148, priority access","Night in a Bedouin-style desert conservation camp","Falconry at dawn with a master falconer","Old Dubai — creek abras, gold and spice souks","Dinner with fountain views at Armani/Amal","Museum of the Future timed entry"]'::jsonb,
   '[{"day":1,"title":"Arrival","description":"Fast-track immigration and transfer to your Downtown tower. Evening at the Dubai Fountain and dinner overlooking the show."},{"day":2,"title":"Vertical city","description":"Burj Khalifa level 148 in the morning light, Museum of the Future after lunch, golden hour at the Palm''s West Beach."},{"day":3,"title":"The old town","description":"Abra across the creek, gold and spice souks, Al Fahidi''s wind-tower lanes and Emirati lunch at a heritage house. Marina yacht cruise at sunset."},{"day":4,"title":"Into the desert","description":"Out to a conservation reserve — dune drive, falconry, camel caravan at sunset, dinner under the stars and a night in canvas luxury."},{"day":5,"title":"Departure","description":"Desert sunrise and transfer to DXB."}]'::jsonb,
   '["Three nights five-star Downtown, one night desert camp","Burj Khalifa level 148 tickets","Falconry session and dune safari","Private airport and city transfers","Daily breakfast, desert dinner under the stars","Marina sunset yacht cruise"]'::jsonb,
   '["International flights","UAE visa fees","Lunches and most dinners","Travel insurance","Theme park tickets"]'::jsonb,
   '[{"name":"Address Downtown","stars":5,"location":"Downtown Dubai","image":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=75"},{"name":"Al Maha Desert Resort","stars":5,"location":"Dubai Desert Conservation Reserve","image":"https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Abu Dhabi day trip","distance":"140 km from Dubai","description":"Sheikh Zayed Grand Mosque and the Louvre Abu Dhabi."},{"name":"Hatta","distance":"130 km from Dubai","description":"Kayaks and mountain trails in the Hajar range."},{"name":"Global Village","distance":"20 km from Downtown","description":"Ninety pavilions of food and folklore, in season."}]'::jsonb,
   '[{"author":"Farah Sheikh","origin":"Karachi","rating":4.9,"comment":"The desert night rebalanced the whole trip — the skyline means more after the silence.","month_year":"January 2026"},{"author":"Daniel Okafor","origin":"Lagos","rating":4.7,"comment":"Level 148 with no queue. That''s how Dubai should be done.","month_year":"December 2025"}]'::jsonb,
   25.2048, 55.2708, 'Dubai Luxury Packages — Skyline, Souks & Desert Camps', 'Burj Khalifa priority access, falconry at dawn and conservation-reserve nights.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('bali', 'Bali', 'Indonesia', 'Island of a thousand temples, and one long exhale',
   'Bali layers jungle, rice terrace and reef around a living Hindu culture that scents every morning with frangipani and incense. We base you between Ubud''s green canyons and Uluwatu''s clifftops: private villa pools, water temple blessings, sunrise on Mount Batur and dinners where the paddies glow gold.',
   'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/1093662/1093662-hd_1920_1080_30fps.mp4', 64500, 7, 6,
   'April – October', 4.9, 1873, true,
   '["Honeymoon","Luxury","International"]'::jsonb,
   '["Private pool villa in the Ubud jungle","Water blessing ritual at Tirta Empul","Sunrise trek (or jeep) up Mount Batur","Tegallalang terraces before the day begins","Uluwatu clifftop kecak fire dance at sunset","Floating breakfast and couples spa ritual"]'::jsonb,
   '[{"day":1,"title":"Arrival — Ubud","description":"VIP airport meet and the drive into the hills. Your villa''s pool faces pure jungle; dinner is served on your deck."},{"day":2,"title":"Sacred water","description":"Morning blessing at Tirta Empul with a village priest, then Gunung Kawi''s rock-cut shrines and lunch above the Petanu gorge."},{"day":3,"title":"Batur sunrise","description":"Pre-dawn ascent for sunrise over the caldera, hot springs after, and an afternoon nap you''ve earned. Evening in Ubud''s galleries."},{"day":4,"title":"Terraces and temples","description":"Tegallalang at first light, a Balinese cooking class in a family compound, and the monkey forest at closing time."},{"day":5,"title":"South to the cliffs","description":"Transfer to an Uluwatu clifftop resort. Sunset kecak fire dance at the temple, dinner on the rocks at Jimbaran bay."},{"day":6,"title":"Reef and swell","description":"Morning snorkel or surf lesson at Padang Padang, floating breakfast, couples spa ritual as the sun drops."},{"day":7,"title":"Departure","description":"Slow morning and private transfer to DPS."}]'::jsonb,
   '["Four nights Ubud pool villa, two nights clifftop resort","All experiences with private driver-guide","Batur sunrise with breakfast","Couples spa ritual and floating breakfast","Daily breakfast, three curated dinners","VIP airport handling"]'::jsonb,
   '["International flights","Indonesia visa on arrival","Lunches except cooking class day","Travel insurance","Personal expenses"]'::jsonb,
   '[{"name":"Hanging Gardens of Bali","stars":5,"location":"Payangan, Ubud","image":"https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=75"},{"name":"Six Senses Uluwatu","stars":5,"location":"Uluwatu","image":"https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Nusa Penida","distance":"45 min by fast boat","description":"Kelingking''s T-rex cliff and manta bays."},{"name":"Sidemen valley","distance":"40 km from Ubud","description":"The Bali of thirty years ago, under Mount Agung."},{"name":"Menjangan reef","distance":"North-west national park","description":"The island''s clearest water and wall dives."}]'::jsonb,
   '[{"author":"Aisha & Omar Qureshi","origin":"Dubai","rating":5.0,"comment":"The water blessing undid two years of city stress. A perfect honeymoon.","month_year":"September 2025"},{"author":"Rachel Kim","origin":"Seoul","rating":4.8,"comment":"Every transfer smooth, every table booked right.","month_year":"June 2026"}]'::jsonb,
   -8.5069, 115.2625, 'Bali Honeymoons & Escapes — Ubud Villas to Uluwatu Cliffs', 'Pool villas, water temple blessings and Batur sunrises, privately guided.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('maldives', 'Maldives', 'Maldives', 'One island, one resort, one shade of impossible blue',
   'The Maldives perfected the argument for doing nothing: an overwater villa with a glass floor, a house reef three steps away, and horizons unbroken in every direction. We match you to the right atoll and resort — seaplane arrivals, sandbank picnics, sunset dolphin cruises and dinners below sea level.',
   'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1476673160081-cf065607f449?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/2169880/2169880-uhd_3840_2160_30fps.mp4', 89000, 5, 4,
   'November – April', 4.9, 1621, true,
   '["Honeymoon","Luxury","International"]'::jsonb,
   '["Overwater villa with private pool and glass floor","Seaplane transfer over the atolls","Guided house-reef snorkel with a marine biologist","Private sandbank picnic, just the two of you","Sunset dolphin cruise","Underwater restaurant dinner"]'::jsonb,
   '[{"day":1,"title":"Seaplane in","description":"The forty-minute flight is the best welcome in travel. Champagne check-in, first swim off your villa deck."},{"day":2,"title":"The reef","description":"Morning snorkel safari with the resident marine biologist — turtles, rays, reef sharks. Afternoon spa over the lagoon."},{"day":3,"title":"Sandbank day","description":"Dropped by dhoni on a private sandbank with a hamper and a parasol. Evening dolphin cruise as the sky performs."},{"day":4,"title":"Blue at leisure","description":"Yours entirely — dive, kayak, or do gloriously little. Farewell dinner below the surface at the reef restaurant."},{"day":5,"title":"Departure","description":"Last glass-floor morning and the seaplane to Malé."}]'::jsonb,
   '["Four nights overwater pool villa, half board","Return seaplane transfers","Marine-biologist reef safari","Private sandbank picnic","Sunset dolphin cruise","Underwater restaurant dinner"]'::jsonb,
   '["International flights to Malé","Lunches and premium beverages","Diving courses","Travel insurance","Green tax where applicable"]'::jsonb,
   '[{"name":"Soneva Jani","stars":5,"location":"Noonu Atoll","image":"https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1000&q=75"},{"name":"Conrad Maldives Rangali","stars":5,"location":"South Ari Atoll","image":"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Hanifaru Bay","distance":"Baa Atoll","description":"Seasonal manta and whale-shark gatherings."},{"name":"Malé old town","distance":"Capital island","description":"Coral-stone mosques and the fish market."},{"name":"Vaadhoo bioluminescence","distance":"Raa Atoll","description":"The famous sea of stars on dark nights."}]'::jsonb,
   '[{"author":"Zara & Imran Ali","origin":"London","rating":5.0,"comment":"The sandbank picnic was the most romantic hour of our lives. Nothing was too much trouble.","month_year":"March 2026"},{"author":"Hiroshi Tanaka","origin":"Tokyo","rating":4.9,"comment":"Resort selection was spot on. The reef is world class.","month_year":"February 2026"}]'::jsonb,
   3.2028, 73.2207, 'Maldives Overwater Villas — Seaplanes, Reefs & Sandbanks', 'Hand-matched resorts, marine-biologist safaris and dinners under the sea.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('singapore', 'Singapore', 'Singapore', 'A garden that became a city',
   'Singapore compresses a continent into an island: hawker stalls with Michelin stars, a rainforest inside an airport, supertrees that sing at night. Ideal for families and first international trips, our itineraries thread Gardens by the Bay, Sentosa and the shophouse neighbourhoods with zero friction.',
   'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1508964942454-1a56651d54ac?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1496939376851-89342e90adcd?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1490642914619-7955a3fd483c?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1565967511849-76a60a516170?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1530521954074-e64f6810b32d?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/1093662/1093662-hd_1920_1080_30fps.mp4', 52000, 5, 4,
   'Year-round', 4.7, 1342, false,
   '["Family","International","City"]'::jsonb,
   '["Gardens by the Bay with Supertree Grove light show","Universal Studios express passes","Hawker trail with a food historian","Night Safari tram with priority boarding","Marina Bay Sands SkyPark at sunset","Katong shophouse and Peranakan heritage walk"]'::jsonb,
   '[{"day":1,"title":"Arrival","description":"Jewel''s rain vortex on the way out of Changi. Evening at Marina Bay — SkyPark at golden hour, Spectra light show after."},{"day":2,"title":"Gardens and bays","description":"Cloud Forest and Flower Dome in the morning cool, ArtScience Museum after lunch, Supertree Grove rhapsody at night."},{"day":3,"title":"Sentosa","description":"Universal Studios with express passes, cable car across the harbour, sunset at Tanjong Beach."},{"day":4,"title":"Heritage and hawkers","description":"Katong''s Peranakan shophouses, Chinatown and Little India with a food historian — chilli crab finale. Night Safari to close."},{"day":5,"title":"Departure","description":"Orchard Road morning or straight to Jewel early."}]'::jsonb,
   '["Four nights in a Marina Bay-view hotel","Universal Studios with express passes","Gardens by the Bay and Night Safari entries","Hawker trail with historian guide","Private airport transfers","Daily breakfast"]'::jsonb,
   '["International flights","Most lunches and dinners","Travel insurance","Personal shopping","Optional attraction upgrades"]'::jsonb,
   '[{"name":"Marina Bay Sands","stars":5,"location":"Marina Bay","image":"https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1000&q=75"},{"name":"The Fullerton Hotel","stars":5,"location":"Fullerton Square","image":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Pulau Ubin","distance":"Bumboat from Changi","description":"Kampong Singapore, preserved on a bicycle-sized island."},{"name":"Southern Ridges","distance":"Harbourfront","description":"Treetop walkways linking forest parks."},{"name":"Tiong Bahru","distance":"Central","description":"Art-deco estate of bakeries and bookshops."}]'::jsonb,
   '[{"author":"The Guptas","origin":"Ahmedabad","rating":4.8,"comment":"With two kids under ten this was flawless. Express passes were worth everything.","month_year":"May 2026"},{"author":"Wei Ling Tan","origin":"Kuala Lumpur","rating":4.6,"comment":"The hawker trail found stalls even I didn''t know.","month_year":"April 2026"}]'::jsonb,
   1.3521, 103.8198, 'Singapore Family Holidays — Gardens, Sentosa & Hawker Trails', 'Express-pass theme parks, supertree nights and food-historian tours.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('thailand', 'Thailand', 'Thailand', 'Golden temples, jade water, open kitchens',
   'Thailand moves from Bangkok''s gilded chaos to limestone bays where the sea turns to glass. Our route pairs the capital''s temples and canal life with Phuket and Phang Nga''s island world — longtail boats to Maya Bay at dawn, beach clubs at dusk, and massaman curry from its birthplace.',
   'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1476673160081-cf065607f449?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/1093662/1093662-hd_1920_1080_30fps.mp4', 46500, 6, 5,
   'November – April', 4.7, 1518, false,
   '["Family","Honeymoon","International"]'::jsonb,
   '["Grand Palace and Wat Arun with a historian","Longtail canal tour through Thonburi","Phang Nga Bay by private speedboat at dawn","Beachfront resort on Kata''s golden crescent","Thai cooking class in a Phuket home","Old Phuket Town''s Sino-Portuguese streets"]'::jsonb,
   '[{"day":1,"title":"Bangkok arrival","description":"Riverside hotel check-in, sunset drinks facing Wat Arun, dinner at a canal-side kitchen."},{"day":2,"title":"Royal Bangkok","description":"Grand Palace and the Emerald Buddha early, Wat Pho''s reclining giant, then longtails through Thonburi''s canal life."},{"day":3,"title":"South to Phuket","description":"Morning flight, afternoon on Kata beach, sunset at the Karon viewpoint."},{"day":4,"title":"Phang Nga at dawn","description":"Private speedboat before the flotillas — James Bond island, Hong lagoons by canoe, lunch on Naka Yai."},{"day":5,"title":"Taste of the south","description":"Market-to-table cooking class in a local home, Old Phuket Town walk, farewell beach-club sunset."},{"day":6,"title":"Departure","description":"Beach morning and transfer to HKT."}]'::jsonb,
   '["Two nights Bangkok riverside, three nights Phuket beachfront","Domestic flight Bangkok–Phuket","Private Phang Nga speedboat charter","Historian-led temple mornings","Cooking class with market visit","Daily breakfast and all transfers"]'::jsonb,
   '["International flights","Most lunches and dinners","Travel insurance","Spa treatments","Personal expenses"]'::jsonb,
   '[{"name":"The Siam","stars":5,"location":"Bangkok riverside","image":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=75"},{"name":"The Shore at Katathani","stars":5,"location":"Kata Noi, Phuket","image":"https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Ayutthaya","distance":"80 km from Bangkok","description":"The ruined royal capital among banyan roots."},{"name":"Similan Islands","distance":"Boat from Khao Lak","description":"Thailand''s clearest dive water, in season."},{"name":"Big Buddha","distance":"6 km from Chalong","description":"Forty-five metres of white marble above the island."}]'::jsonb,
   '[{"author":"Neha & Vivaan Joshi","origin":"Indore","rating":4.8,"comment":"Phang Nga before the crowds was magic. The kids graduated from pad thai to green curry.","month_year":"December 2025"},{"author":"Lucas Meyer","origin":"Berlin","rating":4.6,"comment":"Bangkok guide was outstanding. Smooth throughout.","month_year":"January 2026"}]'::jsonb,
   7.8804, 98.3923, 'Thailand Journeys — Bangkok Temples to Phang Nga Bays', 'Private speedboats, historian-led temples and beachfront Phuket stays.')
on conflict (slug) do nothing;

insert into public.destinations
  (slug, name, country, tagline, overview, hero_image, card_image,
   gallery, video_url, price_from, days, nights, best_season, rating,
   review_count, featured, tags, highlights, itinerary, included,
   excluded, hotels, attractions, reviews, latitude, longitude,
   seo_title, seo_description)
values
  ('switzerland', 'Switzerland', 'Switzerland', 'Punctual trains through impossible scenery',
   'Switzerland is the world''s most beautiful timetable: panoramic trains that thread glaciers, lakes with alps for walls, villages where cars were never invited. We build it around the Glacier Express, Zermatt''s Matterhorn mornings, Interlaken''s adventure valley and Lucerne''s medieval waterfront.',
   'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1800&q=80', 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1000&q=75',
   '["https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=1800&q=80"]'::jsonb,
   'https://videos.pexels.com/video-files/3571264/3571264-uhd_3840_2160_30fps.mp4', 145000, 8, 7,
   'May – October, December – March', 4.9, 987, true,
   '["Luxury","Honeymoon","International"]'::jsonb,
   '["Glacier Express in Excellence Class","Matterhorn sunrise from Gornergrat","Jungfraujoch — Top of Europe","Lake Lucerne paddle steamer cruise","Chocolate and cheese masterclass in Gruyères","Car-free Zermatt and Mürren villages"]'::jsonb,
   '[{"day":1,"title":"Zürich to Lucerne","description":"Arrive and rail to Lucerne. Chapel Bridge, old-town frescoes, dinner on the lakefront."},{"day":2,"title":"Lake Lucerne","description":"Paddle steamer to Vitznau, cogwheel up Rigi for the classic panorama, fondue back in town."},{"day":3,"title":"Interlaken","description":"GoldenPass line through the Brünig pass. Afternoon at Lake Brienz''s turquoise, evening in Unterseen''s lanes."},{"day":4,"title":"Jungfraujoch","description":"The railway through the Eiger to 3,454 metres — ice palace, glacier plateau. Cliffside Mürren by cable car on the return."},{"day":5,"title":"To Zermatt","description":"Rail through the Rhône valley to the car-free village under the Matterhorn. Electric-taxi arrival, first sight of the peak."},{"day":6,"title":"Gornergrat sunrise","description":"Dawn cogwheel to 3,089 metres as the Matterhorn catches fire. Afternoon walk to Riffelsee''s mirror."},{"day":7,"title":"Glacier Express","description":"The famous eight-hour crossing to St. Moritz in Excellence Class — 291 bridges, 91 tunnels, five-course lunch at your seat."},{"day":8,"title":"Departure","description":"Engadin morning and rail to Zürich airport."}]'::jsonb,
   '["Seven nights four/five-star alpine hotels","Swiss Travel Pass first class","Glacier Express Excellence Class with lunch","Jungfraujoch and Gornergrat tickets","Gruyères masterclass","Daily breakfast and four dinners"]'::jsonb,
   '["International flights","Schengen visa fees","Most lunches","Travel insurance","Ski passes and rentals"]'::jsonb,
   '[{"name":"Hotel Schweizerhof","stars":5,"location":"Lucerne","image":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=75"},{"name":"Victoria-Jungfrau Grand","stars":5,"location":"Interlaken","image":"https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=75"},{"name":"Mont Cervin Palace","stars":5,"location":"Zermatt","image":"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1000&q=75"}]'::jsonb,
   '[{"name":"Lauterbrunnen valley","distance":"12 km from Interlaken","description":"Seventy-two waterfalls in one glacial trench."},{"name":"Aletsch glacier","distance":"Above Fiesch","description":"The Alps'' longest river of ice, UNESCO-listed."},{"name":"St. Moritz","distance":"Engadin valley","description":"The original winter resort, champagne air included."}]'::jsonb,
   '[{"author":"Rajeev & Sunita Talwar","origin":"Delhi","rating":5.0,"comment":"Excellence Class on the Glacier Express is the finest day of travel money can buy.","month_year":"June 2026"},{"author":"Grace Chen","origin":"Singapore","rating":4.9,"comment":"Every train, every seat reservation, every transfer — perfect.","month_year":"September 2025"}]'::jsonb,
   46.8182, 8.2275, 'Switzerland by Rail — Glacier Express, Zermatt & Jungfrau', 'Excellence Class rail journeys, Matterhorn sunrises and lakefront grand hotels.')
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('grand-himalayan-odyssey', 'Grand Himalayan Odyssey', 'luxury',
   'Kashmir''s houseboats to Ladakh''s lakes in one seamless arc — private hosts, luxury camps and the mountains at their most generous.',
   'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1000&q=75', 118000, 12, 11,
   '["Srinagar","Gulmarg","Kargil","Leh","Nubra","Pangong"]'::jsonb,
   '["Dal Lake houseboat suite","Drive the Srinagar–Leh highway","Luxury camps at Nubra and Pangong","Private monastery audiences"]'::jsonb,
   true, 4.9)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('spice-coast-immersion', 'Spice Coast Immersion', 'premium',
   'Kochi, Munnar, the backwaters and Marari''s quiet sands — Kerala''s full spectrum with plantation bungalows and a private houseboat.',
   'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=75', 52000, 8, 7,
   '["Kochi","Munnar","Thekkady","Alleppey","Marari"]'::jsonb,
   '["Kolukkumalai sunrise jeep safari","Exclusive-use kettuvallam","Periyar spice trail","Beachfront finale at Marari"]'::jsonb,
   true, 4.8)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('maldives-celebration', 'Maldives Celebration', 'honeymoon',
   'Overwater pool villa, seaplane arrival, sandbank picnic and a dinner under the sea — the definitive beginning.',
   'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1000&q=75', 138000, 5, 4,
   '["Malé","Noonu Atoll"]'::jsonb,
   '["Overwater villa with private pool","Private sandbank picnic","Underwater restaurant dinner","Couples spa over the lagoon"]'::jsonb,
   true, 4.9)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('bali-two-worlds', 'Bali: Jungle & Cliff', 'honeymoon',
   'Four nights in an Ubud jungle villa, two on Uluwatu''s cliffs — blessings, Batur sunrise and fire dances at the edge of the sea.',
   'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=75', 96500, 7, 6,
   '["Ubud","Kintamani","Uluwatu","Jimbaran"]'::jsonb,
   '["Private pool villa in the jungle","Tirta Empul water blessing","Mount Batur sunrise","Kecak fire dance at Uluwatu"]'::jsonb,
   true, 4.9)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('alpine-grand-tour', 'Alpine Grand Tour', 'vip',
   'Switzerland end to end in Excellence Class — Glacier Express, Jungfraujoch, Gornergrat sunrise and grand hotels on every lake.',
   'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1000&q=75', 285000, 10, 9,
   '["Zürich","Lucerne","Interlaken","Zermatt","St. Moritz"]'::jsonb,
   '["Glacier Express Excellence Class","Top of Europe at Jungfraujoch","Matterhorn sunrise from Gornergrat","Five-star lakefront grand hotels"]'::jsonb,
   true, 5.0)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('ladakh-high-passes', 'Ladakh High Passes Expedition', 'adventure',
   'Khardung La, Nubra''s dunes and a lakeshore camp at Pangong — oxygen-equipped SUVs and crews that know every hairpin.',
   'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=75', 48500, 7, 6,
   '["Leh","Khardung La","Nubra","Pangong Tso"]'::jsonb,
   '["One of the world''s highest motorable passes","Bactrian camels at Hunder","Luxury lakeshore camping","Astronomer-led stargazing"]'::jsonb,
   false, 4.8)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('singapore-family-week', 'Singapore Family Week', 'family',
   'Express passes, night safaris and supertrees that sing — the easiest international trip a family can take.',
   'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1000&q=75', 68000, 6, 5,
   '["Marina Bay","Sentosa","Katong"]'::jsonb,
   '["Universal Studios express entry","Night Safari priority tram","Gardens by the Bay light show","Hawker trail for young palates"]'::jsonb,
   false, 4.7)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('royal-rajasthan-express', 'Royal Rajasthan in Brief', 'weekend',
   'A long weekend inside the pink city — havelis, Amber at dawn and a balloon over the Aravallis.',
   'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1000&q=75', 24500, 4, 3,
   '["Jaipur","Amber","Sanganer"]'::jsonb,
   '["Heritage haveli stay","Hot-air balloon flight","Historian-led Amber Fort","Palace courtyard dinner"]'::jsonb,
   false, 4.7)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('goa-slow-coast', 'Goa Slow Coast', 'budget',
   'The south coast, heritage lanes and a sunset sail — Goa''s good life at an honest price.',
   'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=75', 13900, 4, 3,
   '["Betalbatim","Fontainhas","Old Goa"]'::jsonb,
   '["Boutique stay near quiet sands","Latin Quarter heritage walk","Spice farm lunch","Group catamaran sunset"]'::jsonb,
   false, 4.5)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('thai-island-classic', 'Thai Island Classic', 'international',
   'Bangkok''s golden temples then Phuket''s jade bays — the classic first taste of Southeast Asia, elevated.',
   'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1000&q=75', 58500, 6, 5,
   '["Bangkok","Phuket","Phang Nga"]'::jsonb,
   '["Grand Palace with a historian","Private Phang Nga speedboat","Beachfront Kata resort","Home cooking class"]'::jsonb,
   false, 4.7)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('nilgiri-blue-weekend', 'Nilgiri Blue Weekend', 'weekend',
   'Toy train up, butler-run bungalow, planter''s tea tasting — the hills as the Raj kept them.',
   'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=75', 16900, 4, 3,
   '["Mettupalayam","Coonoor","Ooty"]'::jsonb,
   '["Reserved heritage rail coach","Raj-era bungalow with butler","Estate tasting with the planter","Avalanche lake picnic"]'::jsonb,
   false, 4.6)
on conflict (slug) do nothing;

insert into public.packages
  (slug, name, category, description, image, price, days, nights,
   route, highlights, featured, rating)
values
  ('dubai-desert-and-sky', 'Dubai: Desert & Sky', 'luxury',
   'Level 148 by day, conservation-reserve silence by night — both Dubais in one unhurried itinerary.',
   'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1000&q=75', 89000, 5, 4,
   '["Downtown Dubai","Old Dubai","Al Marmoom Desert"]'::jsonb,
   '["Burj Khalifa priority level 148","Falconry at dawn","Night in a luxury desert camp","Marina sunset yacht"]'::jsonb,
   true, 4.8)
on conflict (slug) do nothing;

insert into public.gallery (image, caption, location, category, aspect_ratio)
select * from (values
  ('https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1800&q=80', 'Kettuvallam at first light', 'Alleppey, Kerala', 'India', 1.5),
  ('https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1800&q=80', 'The lagoon holds its breath', 'Noonu Atoll, Maldives', 'Beaches', 0.75),
  ('https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1800&q=80', 'Prayer flags at the pass', 'Ladakh', 'Mountains', 1.4),
  ('https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1800&q=80', 'Terraces of Tegallalang', 'Ubud, Bali', 'International', 0.8),
  ('https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1800&q=80', 'The palace of winds', 'Jaipur, Rajasthan', 'Heritage', 0.7),
  ('https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1800&q=80', 'Lake Lucerne, mid-crossing', 'Switzerland', 'International', 1.5),
  ('https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1800&q=80', 'Blue hour on the marina', 'Dubai', 'Cities', 1.3),
  ('https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=1800&q=80', 'Fifty shades of green', 'Munnar, Kerala', 'India', 0.8),
  ('https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1800&q=80', 'Wat Arun from the river', 'Bangkok, Thailand', 'Heritage', 0.75),
  ('https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1800&q=80', 'The long afternoon', 'South Goa', 'Beaches', 1.5),
  ('https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=80', 'Cedar line, snow line', 'Manali, Himachal', 'Mountains', 1.4),
  ('https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1800&q=80', 'Gardens by the Bay', 'Singapore', 'Cities', 1.3),
  ('https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1800&q=80', 'Atoll geometry', 'Maldives', 'Beaches', 1.4),
  ('https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1800&q=80', 'First sun through the valley', 'Kashmir', 'Mountains', 1.5),
  ('https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=80', 'Estate road, Kodagu', 'Coorg, Karnataka', 'India', 1.5),
  ('https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1800&q=80', 'Gates of heaven', 'Bali, Indonesia', 'Heritage', 0.7),
  ('https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1800&q=80', 'The Matterhorn declines to pose', 'Zermatt, Switzerland', 'Mountains', 0.8),
  ('https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1800&q=80', 'Longtail, limestone, jade', 'Krabi, Thailand', 'Beaches', 0.75)
) as v(image, caption, location, category, aspect_ratio)
where not exists (select 1 from public.gallery where deleted_at is null);

insert into public.testimonials (name, origin, avatar, rating, quote, trip_name)
select * from (values
  ('Ananya & Dev Iyer', 'Bengaluru, India', 'https://randomuser.me/api/portraits/women/44.jpg', 5.0, 'Aurevia didn''t plan our honeymoon — they directed it. Every sunset seemed to arrive on cue. We came home different people.', 'Maldives Celebration'),
  ('James Whitmore', 'London, UK', 'https://randomuser.me/api/portraits/men/32.jpg', 5.0, 'I''ve used travel designers on four continents. Nobody sweats the details like this team — the houseboat playlist matched the sunset.', 'Spice Coast Immersion'),
  ('Farah Sheikh', 'Dubai, UAE', 'https://randomuser.me/api/portraits/women/68.jpg', 4.9, 'Ladakh at those altitudes could have been an ordeal. Instead it was the most comfortable adventure of my life.', 'High Passes Expedition'),
  ('The Gupta Family', 'Ahmedabad, India', 'https://randomuser.me/api/portraits/men/75.jpg', 4.8, 'Two kids, four grandparents, zero meltdowns. Singapore with Aurevia was the first holiday where we all actually rested.', 'Singapore Family Week'),
  ('Charlotte Dubois', 'Paris, France', 'https://randomuser.me/api/portraits/women/17.jpg', 5.0, 'The balloon over Amber at dawn, the palace dinner by oil lamp — Jaipur was staged like an opera and we had the royal box.', 'Royal Rajasthan'),
  ('Rajeev Talwar', 'New Delhi, India', 'https://randomuser.me/api/portraits/men/54.jpg', 5.0, 'Excellence Class on the Glacier Express, arranged down to the window side. Switzerland by Aurevia is the only way I''ll do it again.', 'Alpine Grand Tour')
) as v(name, origin, avatar, rating, quote, trip_name)
where not exists (select 1 from public.testimonials where deleted_at is null);

insert into public.faqs (question, answer, category)
select * from (values
  ('How far in advance should I book my journey?', 'For international journeys and peak seasons (December–January, April–May) we recommend 60–90 days, which secures the best villas, rail classes and guides. Domestic escapes can often be arranged within two to three weeks. For the Maldives and Switzerland in high season, earlier is always better.', 'Booking'),
  ('Are your itineraries customisable?', 'Entirely. Every published itinerary is a starting sketch — our travel designers rebuild it around your dates, pace, cuisine preferences and occasions. Roughly 80% of the journeys we operate are bespoke variations of our core routes.', 'Booking'),
  ('What is included in the published price?', 'Each destination page lists inclusions and exclusions precisely. As a rule: stays, private transfers, named experiences, listed meals and your destination host are included; flights to the starting point, visas and insurance are not. There are no hidden fees — the quote you approve is the price you pay.', 'Pricing'),
  ('How do payments and cancellations work?', 'A 25% deposit confirms your journey; the balance is due 30 days before departure. Cancellations more than 45 days out are refunded minus non-recoverable supplier costs; within 45 days, our team works to recover and re-credit whatever the hotels and operators allow. We always recommend comprehensive travel insurance.', 'Pricing'),
  ('Do you assist with visas and travel insurance?', 'Yes. Our documentation desk prepares your visa file, books appointments and tracks applications for every destination we operate. We also partner with leading insurers for trip, medical and high-altitude cover, and will recommend the right policy for your route.', 'Travel'),
  ('Is support available while I''m travelling?', 'Every journey runs with a dedicated destination host and a 24/7 concierge line. Flight delayed, weather turned, restaurant closed — one message and the itinerary reshapes around you in real time.', 'Travel'),
  ('Can you arrange journeys for large families or corporate groups?', 'Group journeys are a speciality — multi-generation family reunions, incentive trips, offsites and destination celebrations up to 120 guests. We handle rooming, dietaries, staggered arrivals, event production and on-ground crew.', 'Groups'),
  ('Which destinations suit first-time international travellers?', 'Singapore, Dubai and Thailand are our gentlest introductions — short flights from India, simple visas, and infrastructure that forgives every wrong turn. Bali follows closely for couples. Our designers will match the destination to your comfort level.', 'Travel')
) as v(question, answer, category)
where not exists (select 1 from public.faqs where deleted_at is null);
