// Generates supabase/seed_content.sql from the bundled catalogue so the
// production database carries the same content the app ships with.
//
// Run from the project root:
//   dart run tool/generate_seed_sql.dart
import 'dart:convert';
import 'dart:io';

import 'package:aurevia/data/seed/seed_content.dart';
import 'package:aurevia/data/seed/seed_destinations.dart';

String q(String value) => "'${value.replaceAll("'", "''")}'";

String j(Object value) => "${q(jsonEncode(value))}::jsonb";

void main() {
  final buffer = StringBuffer()
    ..writeln('-- ============================================================')
    ..writeln('-- AUREVIA — content seed (generated by tool/generate_seed_sql.dart)')
    ..writeln('-- Loads the full catalogue into Supabase. Idempotent:')
    ..writeln('--   destinations/packages skip rows whose slug already exists;')
    ..writeln('--   gallery/testimonials/faqs only load into an empty table.')
    ..writeln('-- Run after schema.sql in the Supabase SQL editor.')
    ..writeln('-- ============================================================')
    ..writeln();

  for (final d in seedDestinations) {
    buffer
      ..writeln('insert into public.destinations')
      ..writeln('  (slug, name, country, tagline, overview, hero_image, card_image,')
      ..writeln('   gallery, video_url, price_from, days, nights, best_season, rating,')
      ..writeln('   review_count, featured, tags, highlights, itinerary, included,')
      ..writeln('   excluded, hotels, attractions, reviews, latitude, longitude,')
      ..writeln('   seo_title, seo_description)')
      ..writeln('values')
      ..writeln('  (${q(d.slug)}, ${q(d.name)}, ${q(d.country)}, ${q(d.tagline)},')
      ..writeln('   ${q(d.overview)},')
      ..writeln('   ${q(d.heroImage)}, ${q(d.cardImage)},')
      ..writeln('   ${j(d.gallery)},')
      ..writeln('   ${q(d.videoUrl)}, ${d.priceFrom}, ${d.days}, ${d.nights},')
      ..writeln('   ${q(d.bestSeason)}, ${d.rating}, ${d.reviewCount}, ${d.featured},')
      ..writeln('   ${j(d.tags)},')
      ..writeln('   ${j(d.highlights)},')
      ..writeln('   ${j(d.itinerary.map((e) => e.toJson()).toList())},')
      ..writeln('   ${j(d.included)},')
      ..writeln('   ${j(d.excluded)},')
      ..writeln('   ${j(d.hotels.map((e) => e.toJson()).toList())},')
      ..writeln('   ${j(d.attractions.map((e) => e.toJson()).toList())},')
      ..writeln('   ${j(d.reviews.map((e) => e.toJson()).toList())},')
      ..writeln('   ${d.latitude}, ${d.longitude}, ${q(d.seoTitle)}, ${q(d.seoDescription)})')
      ..writeln('on conflict (slug) do nothing;')
      ..writeln();
  }

  for (final p in seedPackages) {
    buffer
      ..writeln('insert into public.packages')
      ..writeln('  (slug, name, category, description, image, price, days, nights,')
      ..writeln('   route, highlights, featured, rating)')
      ..writeln('values')
      ..writeln('  (${q(p.slug)}, ${q(p.name)}, ${q(p.category.name)},')
      ..writeln('   ${q(p.description)},')
      ..writeln('   ${q(p.image)}, ${p.price}, ${p.days}, ${p.nights},')
      ..writeln('   ${j(p.route)},')
      ..writeln('   ${j(p.highlights)},')
      ..writeln('   ${p.featured}, ${p.rating})')
      ..writeln('on conflict (slug) do nothing;')
      ..writeln();
  }

  buffer.writeln(
      'insert into public.gallery (image, caption, location, category, aspect_ratio)');
  buffer.writeln('select * from (values');
  buffer.writeln(seedGallery
      .map((g) =>
          '  (${q(g.image)}, ${q(g.caption)}, ${q(g.location)}, ${q(g.category)}, ${g.aspectRatio})')
      .join(',\n'));
  buffer
    ..writeln(') as v(image, caption, location, category, aspect_ratio)')
    ..writeln(
        'where not exists (select 1 from public.gallery where deleted_at is null);')
    ..writeln();

  buffer.writeln(
      'insert into public.testimonials (name, origin, avatar, rating, quote, trip_name)');
  buffer.writeln('select * from (values');
  buffer.writeln(seedTestimonials
      .map((t) =>
          '  (${q(t.name)}, ${q(t.origin)}, ${q(t.avatar)}, ${t.rating}, ${q(t.quote)}, ${q(t.tripName)})')
      .join(',\n'));
  buffer
    ..writeln(') as v(name, origin, avatar, rating, quote, trip_name)')
    ..writeln(
        'where not exists (select 1 from public.testimonials where deleted_at is null);')
    ..writeln();

  buffer.writeln('insert into public.faqs (question, answer, category)');
  buffer.writeln('select * from (values');
  buffer.writeln(seedFaqs
      .map((f) => '  (${q(f.question)}, ${q(f.answer)}, ${q(f.category)})')
      .join(',\n'));
  buffer
    ..writeln(') as v(question, answer, category)')
    ..writeln(
        'where not exists (select 1 from public.faqs where deleted_at is null);');

  File('supabase/seed_content.sql').writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote supabase/seed_content.sql');
}
